### ISSUE TITLE
Can I add multiple robots in this program?

### ISSUE THREAD

**Issue by lgl-960709** [ai-winter/ros_motion_planning#3]
Can I add multiple robots in this program? How do I add them. Thank you very much for your help!

**Comment by ai-winter** [comment]
Hello, @lgl-960709 

Yes, the environment supports multi-agent simulation. Please refer to the `README.md` file, `robot_i` stands for the i-th agent in the environment.

```
map: "warehouse"
world: "warehouse"
robots_config:
  - robot1_type: "turtlebot3_burger"
    robot1_global_planner: "astar"
    robot1_local_planner: "dwa"
    robot1_x_pos: "0.0"
    robot1_y_pos: "0.0"
    robot1_z_pos: "0.0"
    robot1_yaw: "-1.57"
  - robot2_type: "turtlebot3_burger"
    robot2_global_planner: "jps"
    robot2_local_planner: "pid"
    robot2_x_pos: "-5.0"
    robot2_y_pos: "-7.5"
    robot2_z_pos: "0.0"
    robot2_yaw: "0.0"
robots_init: "robots_rviz_init.yaml"
rviz_file: "sim_env.rviz"
```
