### ISSUE TITLE
change the algorithm

### ISSUE THREAD

**Issue by 1littlestudy** [ai-winter/ros_motion_planning#56]
Hello, I am a beginner and I would like to ask how to change the algorithm for small cars from A * to rrt algorithm,Thank you in advance for your answer

**Comment by ai-winter** [comment]
Hello, @1littlestudy 
`README.md` gives an example in detail, you can also refer to this configure.
```yaml
map: "warehouse"
world: "warehouse"
robots_config:
  - robot1_type: "turtlebot3_burger"
    robot1_global_planner: "astar"
    robot1_local_planner: "dwa"
    robot1_x_pos: "0.0"
    robot1_y_pos: "0.0"
    robot1_z_pos: "0.0"
    robot1_yaw: "-1.57"
  - robot2_type: "turtlebot3_burger"
    robot2_global_planner: "jps"
    robot2_local_planner: "pid"
    robot2_x_pos: "-5.0"
    robot2_y_pos: "-7.5"
    robot2_z_pos: "0.0"
    robot2_yaw: "0.0"
robots_init: "robots_rviz_init.yaml"
rviz_file: "sim_env.rviz"
```

For example, you can change the option `robot1_global_planner` from `astar` to `rrt` to meet your needs
